language: node_js
node_js:
- '7'
branches:
  only:
  - "/^v[0-9]/"
before_deploy:
- npm run build
deploy:
  provider: npm
  email: serveradmin@octoblu.com
  skip_cleanup: true
  api_key:
    secure: asXHIagrN+LkTlVWmuyDEDbu3bsaUu0eaVBT79wDNT433beni0s+eCXewPQUAFdLdOmR4pWPtZMy/bFqh07XhnPHdJGsEBVhV9dVLsErGv0RMRGgjmFt1oelPPpDwUvpx3cJd9e6vm4ddIbN7SerxkWBoHgsG19L0Xn+NcuvZB3nuv++yY+te2LCQ0ytZ8jG6TltDqz9ID6dQjJSnqhAwJChpMsHIEUbnH/eeCO5fmfeuLPZ6YCgVwSoDf+Csx3YKRrPRmjmQ4Cmy8JhMVraN5p9feEyNOo5/9qrSUonkm3dyqVPftavh4PKAUYezsToEw0qXLHuEkAQOYZy2s5rSbf+ksGf6EKrsN2A5Dik9++PqB5AZXbfGXbpZx4GTfK9h9e5DyhnMzbwPzwZ9DITWE7IeP4CYhDs3BV/pCmZO1snVhEVhZcivq9864+TieNDpbgdrj2YfuXmlGrGAKuGWs6nRKwhVkO9LABwv/eh28MR3dej5bqx2NqMhA0hdbAOl2HKStUnG2Uoa0vd/27V9svi8xbcFYIp3y9K0GvmFUWkOoeOPmk39/hnrlFGt/h7apXVw8sspmjfVzP45eJzG2yppYHoITJn1TinciiOefqBGV+BDQwgPTaaJg7ulU5Vc0hX2ljS+GBBTuRGiDPz25oEfwQNZpGfi2BXtuZo32M=
  on:
    tags: true
    branches: true
